export const sample_foods: any[] = [
  {
    id: "1",
    name: "Пицца пепперони",
    cookTime: "10-20",
    price: 10,
    favorite: false,
    origins: ["италия"],
    stars: 4.5,
    imageUrl: "assets/food-1.jpg",
    tags: ["фастфуд", "пицца", "ланч"],
  },
  {
    id: "2",
    name: "Фрикадельки",
    price: 20,
    cookTime: "20-30",
    favorite: true,
    origins: ["персия", "средний восток", "китай"],
    stars: 4.7,
    imageUrl: "assets/food-2.jpg",
    tags: ["слоуфуд", "ланч"],
  },
  {
    id: "3",
    name: "Гамбургер",
    price: 5,
    cookTime: "10-15",
    favorite: false,
    origins: ["германия", "США"],
    stars: 3.5,
    imageUrl: "assets/food-3.jpg",
    tags: ["фастфуд", "гамбургер"],
  },
  {
    id: "4",
    name: "Картошка фри",
    price: 2,
    cookTime: "15-20",
    favorite: true,
    origins: ["бельгия", "франция"],
    stars: 3.3,
    imageUrl: "assets/food-4.jpg",
    tags: ["фастфуд", "жаренное"],
  },
  {
    id: "5",
    name: "Куриный суп",
    price: 11,
    cookTime: "40-50",
    favorite: false,
    origins: ["индия", "ация"],
    stars: 3.0,
    imageUrl: "assets/food-5.jpg",
    tags: ["слоуфуд", "суп"],
  },
  {
    id: "6",
    name: "Вегетерианская пицца",
    price: 9,
    cookTime: "40-50",
    favorite: false,
    origins: ["италия"],
    stars: 4.0,
    imageUrl: "assets/food-6.jpg",
    tags: ["фастфуд", "пицца", "ланч"],
  },
];

export const sample_tags: any[] = [
  { name: "все", count: 6 },
  { name: "фастфуд", count: 4 },
  { name: "пицца", count: 2 },
  { name: "ланч", count: 3 },
  { name: "слоуфуд", count: 2 },
  { name: "гамбургер", count: 1 },
  { name: "жаренное", count: 1 },
  { name: "суп", count: 1 },
];
